/* SELECIONA OS MORADORES APTOS PARA ADOCAO */

SELECT
    M.NOME, M.TELEFONE, M.CEP
FROM
    MORADOR M
WHERE
    (M.RENDA_FAMILIAR/(M.NUM_FILHOS+2) > 1212) /* Renda maior que 1 salário mínimo por pessoa */
AND
    M.NUM_FILHOS <= 2 /* Não mais do que dois filhos */
AND
    M.NUM_PETS <= 1 /* Não mais do que um pet */
AND
    M.IDADE <= 65; /* Idade do responsável menor que 65 */

/* SELECIONA OS ANIMAIS APTOS PARA ADOCAO */

SELECT DISTINCT
    AN.ID_COLEIRA, AN.NOME, AN.CANIL, AN.TIPO, AN.IDADE
FROM
    ANIMAL AN LEFT JOIN ADOCAO AD
ON
    AN.ID_COLEIRA=AD.ANIMAL
WHERE
    AN.ISCASTRADO = 'S' /* Animal castrado */
AND
    AN.ISVERMIFUGADO = 'S' /* Animal vermifugado */
AND
    AN.ID_COLEIRA NOT IN (SELECT ANIMAL FROM ADOCAO) /* Animal ainda não adotado */

/* SELECIONA AS ENTIDADES QUE MAIS DOARAM NA HISTÓRIA */

SELECT
    E.NOME, SUM(C.VALOR) AS VALOR_DOADO
FROM
    ENTIDADE_PARCEIRA E JOIN CONTRIBUICAO C
ON
    E.NOME = C.ENTIDADE
GROUP BY
    E.NOME
ORDER BY
    VALOR_DOADO DESC;

/* SELECIONA TODOS OS ANIMAIS QUE NÃO TOMARAM VACINA PARA
CINMOSE NO ANO CORRENTE (SOMENTE PARA CACHORROS) */

SELECT
    A.NOME
FROM
    ANIMAL A
WHERE
    A.ID_COLEIRA NOT IN
    (
        SELECT A.ID_COLEIRA
        FROM VACINA V JOIN ANIMAL A
        ON V.ANIMAL = A.ID_COLEIRA
        WHERE V.VACINA = 'Cinomose'
        AND EXTRACT(YEAR FROM V.DATA) = EXTRACT(YEAR FROM SYSDATE)
    )
    AND
        A.TIPO='CACHORRO'


/* SELECIONA O NUMERO DE ANIMAIS ADOTADOS POR MÊS E ANO */

SELECT
    EXTRACT(YEAR FROM F.DATA) AS ANO,
    EXTRACT(MONTH FROM F.DATA) AS MES,
    SUM(F.NUM_ANIMAIS_ADOTADOS) AS ANIMAIS_ADOTADOS
FROM
    FEIRA F
GROUP BY
    EXTRACT(YEAR FROM F.DATA),
    EXTRACT(MONTH FROM F.DATA)
